### ISSUE TITLE
Cleanup instructions

### ISSUE THREAD

**Issue by itzhapaz** [lucasschejtman/resttogql-workshop#1]
Hello,

For the cleanup instructions on this page - https://www.appsyncworkshop.com/60_in-summary/61_summary.html you might want to add the following:
- delete the appsync api created manually through the web console
- delete the staging s3 bucket
- if the person created a new cloud9 environment, consider deleting it

**Comment by deekob** [comment]
@itzhapaz - I've added in the additional cleanup instructions - thanks for the feedback
